name: on pull request
on: 
  pull_request:
    branches:
      - main
      - dev
      - qa
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pull request job
        run: echo "pull request raised"
      
