name: secrets and variable
on: workflow_dispatch
jobs:
  secrets:
    env:
      USERNAME: Admin
      PASSWORD: Admin123
    runs-on: ubuntu-latest
    steps:
      - name: login database
        run: echo "login database using password ${{secrets.DB_PASSWORD}} and username ${{vars.DB_USERNAME}}"
      - name: display database credential
        run: echo "Database password is ${{secrets.DB_PASSWORD}} and UserName is ${{vars.DB_USERNAME}}"
    
